title: Resume Named Entity Recognition
description: An exploration project for the [Resume Entities for NER](https://www.kaggle.com/datasets/dataturks/resume-entities-for-ner) problem and dataset.

vars:
  raw_dataset: assets/dataset.jsonl
  train_dataset: corpus/train.spacy
  dev_dataset: corpus/dev.spacy
  dev_ratio: 0.2

directories:
  - assets
  - configs
  - corpus
  - metrics
  - scripts
  - training

assets:
  - dest: ${vars.raw_dataset}
    description: Raw dataset from [Resume Entities for NER](https://www.kaggle.com/datasets/dataturks/resume-entities-for-ner)

workflows:
  all:
    - prepare
    - train
    - evaluate

commands:
  - name: prepare
    help: Prepare the train and dev datasets
    script:
      - python scripts/prepare.py ${vars.raw_dataset} ${vars.train_dataset} ${vars.dev_dataset} --dev-ratio ${vars.dev_ratio}
    deps:
      - scripts/prepare.py
      - ${vars.raw_dataset}
    outputs:
      - ${vars.train_dataset}
      - ${vars.dev_dataset}

  - name: train
    help: Train the model
    script:
      - spacy train configs/scratch_conv_xs.cfg --output training/scratch_conv_xs/
    deps:
      - configs/scratch_conv_xs.cfg
      - ${vars.train_dataset}
      - ${vars.dev_dataset}
    outputs:
      - training/scratch_conv_xs/model-best

  - name: evaluate
    help: Evaluate the model and export metrics
    script:
      - spacy evaluate training/scratch_conv_xs/model-best corpus/dev.spacy --output metrics/scratch_conv_xs.json
    deps:
      - ${vars.dev_dataset}
      - training/scratch_conv_xs/model-best
    outputs:
      - metrics/scratch_conv_xs.json
